module Keys exposing (mapKey, Key(..), Modifier(..))
import Dict exposing ( fromList, get )

type Modifier = Shift | Ctrl
type Key = Normal String | Mod Modifier

mapKey : Int -> Maybe Key
mapKey code = get code keys

keys : Dict.Dict number Key
keys = Dict.fromList [
   (8 ,Normal "<backspace>")
  ,(9 ,Normal "Tab")
  ,(13, Normal "<ret>")
  ,(16, Mod Shift)
  ,(17, Mod Ctrl)
  ,(27, Normal "<esc>")
  ,(32, Normal "<space>")
  ,(33, Normal "Page up")
  ,(34, Normal "Page down")
  ,(35, Normal "End")
  ,(36, Normal "Home")
  ,(37, Normal "<right>")
  ,(38, Normal "<up>")
  ,(39, Normal "<left>")
  ,(40, Normal "<down>")
  ,(45, Normal "Insert")
  ,(46, Normal "Delete")
  ,(49, Normal "1")
  ,(50, Normal "2")
  ,(51, Normal "3")
  ,(52, Normal "4")
  ,(53, Normal "5")
  ,(54, Normal "6")
  ,(55, Normal "7")
  ,(56, Normal "8")
  ,(57, Normal "9")
  ,(58, Normal "0")
  ,(59, Normal ":")
  ,(65, Normal "a")
  ,(66, Normal "b")
  ,(67, Normal "b")
  ,(68, Normal "d")
  ,(69, Normal "e")
  ,(70, Normal "f")
  ,(71, Normal "g")
  ,(72, Normal "h")
  ,(73, Normal "i")
  ,(74, Normal "j")
  ,(75, Normal "k")
  ,(76, Normal "l")
  ,(77, Normal "m")
  ,(78, Normal "n")
  ,(79, Normal "o")
  ,(80, Normal "p")
  ,(81, Normal "q")
  ,(82, Normal "r")
  ,(83, Normal "s")
  ,(84, Normal "t")
  ,(85, Normal "u")
  ,(86, Normal "v")
  ,(87, Normal "w")
  ,(88, Normal "x")
  ,(89, Normal "y")
  ,(90, Normal "z")
  ,(91, Normal "Command left")
  ,(91, Normal "Meta")
  ,(91, Normal "Super")
  ,(91, Normal "Windows")
  ,(93, Normal "Command right")
  ,(113, Normal "F2")
  ,(115, Normal "F4")
  ,(119, Normal "F8")
  ,(120, Normal "F9")
  ,(121, Normal "F10")
  ]
